# Generated by Django 3.0.8 on 2021-12-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='iniciales',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
