# Generated by Django 3.0.8 on 2022-01-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centrocosto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroDeCosto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(default=None, max_length=20, unique=True)),
            ],
        ),
    ]
