# Generated by Django 3.0.8 on 2022-01-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centrocosto', '0002_centrodecosto'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrodecosto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='centrodecosto',
            name='descripcion',
            field=models.CharField(default='centro', max_length=100),
            preserve_default=False,
        ),
    ]
