# Generated by Django 3.0.8 on 2022-01-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centrocosto', '0003_auto_20220115_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='centrodecosto',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
