# Generated by Django 3.0.8 on 2021-12-27 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('centrocosto', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('activa', models.BooleanField(default=True)),
                ('usuarioCaja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarioCaja', to=settings.AUTH_USER_MODEL)),
                ('usuarioCreador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usurioCreador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rendicion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fechaInicioSemana', models.DateTimeField()),
                ('fechaFinalSemana', models.DateTimeField()),
                ('aprobada', models.BooleanField(default=False)),
                ('cerrada', models.BooleanField(default=False)),
                ('Caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendicionCaja', to='caja.Caja')),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('numero', models.CharField(max_length=20, null=True)),
                ('ingreso', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('egreso', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conceptoCaja', to='centrocosto.Concepto')),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gruposCaja', to='centrocosto.Grupo')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectoCaja', to='centrocosto.Proyecto')),
                ('rendicion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registroRendicion', to='caja.Rendicion')),
                ('tipocomprobante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tipoCompCaja', to='centrocosto.TipoComprobante')),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='zonaCaja', to='centrocosto.Zona')),
            ],
        ),
    ]
