# Generated by Django 3.0.8 on 2021-12-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='incremento',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
