# Generated by Django 3.0.8 on 2022-01-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0002_registro_incremento'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendicion',
            name='totalEgreso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='rendicion',
            name='totalIncremento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
