# Generated by Django 3.0.8 on 2022-01-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0003_auto_20220102_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendicion',
            name='saldoCaja',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='rendicion',
            name='totalRendicion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
