# Generated by Django 3.0.8 on 2022-01-15 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centrocosto', '0002_centrodecosto'),
        ('caja', '0004_auto_20220108_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='centrodecosto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='centrodecostoCaja', to='centrocosto.CentroDeCosto'),
        ),
    ]
