# Generated by Django 3.0.8 on 2022-01-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0005_registro_centrodecosto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
