# Generated by Django 3.0.8 on 2022-01-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0006_auto_20220120_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='registro',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='rendicion',
            name='saldoCaja',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='rendicion',
            name='totalEgreso',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='rendicion',
            name='totalIncremento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='rendicion',
            name='totalRendicion',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
